name:                telegram-bot-simple
version:             0.3.8
github:              "fizruk/telegram-bot-simple"
license:             BSD3
author:              "Nickolay Kudasov"
maintainer:          "nickolay.kudasov@gmail.com"
copyright:           "Nickolay Kudasov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Easy to use library for building Telegram bots.
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/fizruk/telegram-bot-simple#readme>

dependencies:
- base >= 4.9 && <5
- aeson
- aeson-pretty
- bytestring
- cron >= 0.7.0
- filepath
- hashable
- http-api-data
- http-client
- http-client-tls
- monad-control
- mtl
- profunctors
- pretty-show
- servant
- servant-client
- servant-multipart
- servant-multipart-client
- servant-multipart-api
- split
- stm
- template-haskell
- text
- time
- transformers
- unordered-containers

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  example-echo-bot:
    main: examples/EchoBot.hs
    dependencies: telegram-bot-simple
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N # -N option provides concurrent running on all available cores.

  example-todo-bot:
    main: examples/TodoBot.hs
    dependencies: telegram-bot-simple
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N # -N option provides concurrent running on all available cores.

  example-game-bot:
    main: examples/GameBot.hs
    dependencies:
      - blaze-html
      - cookie
      - dhall
      - http-types
      - optparse-applicative
      - prettyprinter
      - QuickCheck
      - random
      - servant-blaze
      - servant-server
      - telegram-bot-simple
      - unix
      - uuid
      - warp
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N # -N option provides concurrent running on all available cores.
